batch_size: 16
num_epochs: 10
lr: 0.0001
seq_len: 100
d_model: 256
datasource: opus_books
lang_src: en
lang_tgt: fr
model_filename : translation
model_folder: weights
model_basename: tmodel_
preload: latest
tokenizer_file: tokenizer_{0}.json
experiment_name: runs/tmodel
data_len : 500
