batch_size: 8
num_epochs: 50
lr: 0.0001
seq_len: 150
d_model: 512
datasource: opus_books
lang_src: en
lang_tgt: ta
model_filename : translation
model_folder: weights
model_basename: tmodel_
preload: latest
tokenizer_file: tokenizer_{0}.json
experiment_name: runs/tmodel

