batch_size: 8
num_epochs: 20
lr: 0.0001
seq_len: 400
d_model: 512
datasource: opus_books
lang_src: en
lang_tgt: it
model_folder: weights
model_basename: tmodel_
preload: latest
tokenizer_file: tokenizer_{0}.json
experiment_name: runs/tmodel

